# Generated by Django 4.2.4 on 2023-08-27 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_test_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Date of Birth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
