# Generated by Django 4.2.4 on 2023-08-29 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(default=django.utils.timezone.now, upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
