# Generated by Django 4.2.4 on 2023-08-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_interests_skills_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name_plural': 'Interests'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='interest',
            new_name='interests',
        ),
    ]
